version: '3.4'
# version 3.4. introduces 'target' keyword used in Docker multi-stage builds

#---------------------------------------------------------------------------#
# Used services                                                             #
#---------------------------------------------------------------------------#
services:


#---------------------------------------------------------------------------#
# Ingestion                                                                 #
#---------------------------------------------------------------------------#
  py-ingester:
    build:
      context: ../../../github/annotations-ingester
    environment:
      - SERVICES_USED=elasticsearch-1:9200,elasticsearch-2:9200,elasticsearch-3:9200,gate-nlp-drug:8095
    volumes:
      - ./pipelines/py-ingester/config/config.yml:/app/config/config.yml:ro
    command: "bash run.sh"
    #network_mode: "host"
    networks:
      - nlpnet
      - ingest-documents_esnet

#---------------------------------------------------------------------------#
# NLP services                                                              #
#---------------------------------------------------------------------------#
  gate-nlp-drug:
    build:
      context: ../../../github/nlp-rest-service
      target: service-runner-gate
    volumes:
      # configuration file
      - ./nlp-services/applications/drug-app/config:/app/nlp-service/config:ro
      # GATE app resources
      - ./nlp-services/applications/drug-app/gate:/gate/app/drug-app:ro
    ports:
      - "8095:8095"
    command: "bash /app/nlp-service/run.sh"
    networks:
      - nlpnet


  gate-nlp-bioyodie:
    build:
      context: ../../../github/nlp-rest-service
      target: service-runner-gate
    volumes:
      # configuration files
      - ./nlp-services/applications/bio-yodie/config:/app/nlp-service/config:ro
      # GATE app resources
      - /Users/lroguski/devel/projects/github/bio-YODIE:/gate/app/bioyodie:ro
      - /Users/lroguski/data/UMLS/for-bioyodie/bio-yodie-resources:/gate/app/bioyodie/bio-yodie-resources:ro
    ports:
      - "8096:8095"
    command: "bash /app/nlp-service/run.sh"
    networks:
      - nlpnet


#---------------------------------------------------------------------------#
# Docker networks                                                           #
#---------------------------------------------------------------------------#
networks:
  nlpnet:
    driver: bridge
  ingest-documents_esnet:
    external: true
