version: '3.4'
# version 3.4. introduces 'target' keyword used in Docker multi-stage builds

#---------------------------------------------------------------------------#
# Used services                                                             #
#---------------------------------------------------------------------------#
services:


#---------------------------------------------------------------------------#
# Ingestion                                                                 #
#---------------------------------------------------------------------------#
  py-ingester:
    build:
      context: ../../../github/annotations-ingester
    volumes:
      - ./pipelines/py-ingester/config/config.yml:/app/config.yml:ro
    command: "python main.py --config config.yml"
    network_mode: "host"

#---------------------------------------------------------------------------#
# NLP services                                                              #
#---------------------------------------------------------------------------#
  gate-nlp-drug:
    build:
      context: ../../../github/nlp-rest-service
      target: service-runner-gate
    volumes:
      # configuration file
      - ./nlp-services/applications/drug-app/config:/app/nlp-service/config:ro
      # GATE app resources
      - ./nlp-services/applications/drug-app/gate:/gate/app/drug-app:ro
    ports:
      - "8095:8095"
    command: "bash /app/nlp-service/run.sh"


  gate-nlp-bioyodie:
    build:
      context: ../../../github/nlp-rest-service
      target: service-runner-gate
    volumes:
      # configuration files
      - ./nlp-services/config/bioyodie:/app/nlp-service/config:ro
      - ./nlp-services/run.sh:/app/nlp-service/run.sh:ro
      # GATE app resources
      - /Users/lroguski/devel/projects/github/bio-YODIE:/gate/app/bioyodie:ro
      - /Users/lroguski/data/UMLS/for-bioyodie/bio-yodie-resources:/gate/app/bioyodie/bio-yodie-resources:ro
    ports:
      - "8096:8095"
    command: "bash /app/nlp-service/run.sh"