version: '3.5'

#---------------------------------------------------------------------------#
# Used services                                                             #
#---------------------------------------------------------------------------#
services:


#---------------------------------------------------------------------------#
# Ingestion                                                                 #
#---------------------------------------------------------------------------#
  annotations-ingester:
    image: cogstacksystems/annotations-ingester:latest
    environment:
      - SERVICES_USED=elasticsearch-1:9200,elasticsearch-2:9200,elasticsearch-3:9200,nlp-gate-drug:8095
    volumes:
      - ./pipelines/annotations-ingester/config/config.yml:/app/config/config.yml:ro
    command: "bash run.sh"
    depends_on:
      - nlp-gate-drug
    networks:
      - nlpnet
      - esnet-ext

#---------------------------------------------------------------------------#
# NLP services                                                              #
#---------------------------------------------------------------------------#
  nlp-gate-drug:
    image: cogstacksystems/nlp-rest-service-gate:latest
    volumes:
      # configuration file
      - ./nlp-services/applications/drug-app/config:/app/nlp-service/config:ro
      # GATE app resources
      - ./nlp-services/applications/drug-app/gate:/gate/app/drug-app:ro
    ports:
      - "8095:8095"
    command: "bash /app/nlp-service/run.sh"
    networks:
      - nlpnet


#---------------------------------------------------------------------------#
# Docker networks                                                           #
#---------------------------------------------------------------------------#
networks:
  nlpnet:
    driver: bridge
  esnet-ext:
    external: true
